name: Publish Website

on:
  push:
    branches: # triggers on any push to main
    - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: node --version
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build-prod
    - name: Talks
      run: |
        mkdir -p dist/talks && cd dist/talks
        wget -O research.zip https://www.dropbox.com/s/timotke35xic9uk/strathclyde.zip?dl=0 && unzip research && mv dist research        
        wget -O eds.zip https://www.dropbox.com/s/chfce93cux4v9bh/Presentation.zip?dl=0 && unzip eds && mv Presentation eds
        rm *.zip
        cd ../../
    - name: Apps
      run: |
        mkdir -p dist/apps && cd dist/apps
        wget -O exe.zip https://www.dropbox.com/s/c25yg42ouck6t7c/exe.zip?dl=0 && unzip exe && mv exe rxns
        rm *.zip
        cd ../../
    - name: Blog
      run: |
        cd dist/
        wget -O blog.zip https://www.dropbox.com/s/rmf2qg4byt5v4i9/_site.zip?dl=0 && unzip blog && mv _site blog
        rm *.zip && cd ..
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: thewhitelab.org
